### ISSUE TITLE
Error while setting up ecovent_v2 platform for fan

### ISSUE THREAD

**Issue by circa1665** [gody01/ecovent_v2#1]
When I configure the integration, no devices or entities are created and I have this error the logs:

```
Logger: homeassistant.components.fan
Source: custom_components/ecovent_v2/fan.py:54 
Integration: Fan (documentation, issues) 
First occurred: 19 February 2022, 23:53:43 (2 occurrences) 
Last logged: 00:00:54

Error while setting up ecovent_v2 platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ecovent_v2/fan.py", line 41, in async_setup_entry
    await async_setup_platform(hass, config_entry, async_add_entities)
  File "/config/custom_components/ecovent_v2/fan.py", line 32, in async_setup_platform
    async_add_entities([VentoExpertFan(hass, config)])
  File "/config/custom_components/ecovent_v2/fan.py", line 54, in __init__
    self._percentage = self.man_speed
  File "/usr/local/lib/python3.9/site-packages/ecoventv2/__init__.py", line 529, in man_speed
    return self._man_speed
AttributeError: 'VentoExpertFan' object has no attribute '_man_speed'
```

**Comment by gody01** [comment]
This happens, if home assistant can't communicate with fan.
Can You ping fan's IP address ?
You can enter fan IP address in Host parameter.

**Comment by gody01** [comment]
BTW: Someone posted on original repository also link to another implementation which looks promising and more complete at this time:

https://github.com/dingusdk/ha-dukaone

**Comment by circa1665** [comment]
Yes, I am entering the IP address in Host parameter field. I'm able to ping the fan, it is on a separate subnet to Home Assistant if that makes a difference?

**Comment by gody01** [comment]
It might, If you have blocked port 4000/udp (or tcp) on router between subnets.
I have separate subnets for IoT also and HomeAssistant on other subnet, than fan and it works.

**Comment by sportwerkstatt** [comment]
Hi @gody01, I have the same problem when setting up a fan with this addon. If I set it up via the mentioned ha-dukaone everything seems to be working as expected.
Some additional error logs:
![image](https://user-images.githubusercontent.com/94296729/155884524-0bc2d0e0-e011-46c7-9915-fb846d316127.png)

Both fan and home-assistant reside on the same subnet for now. Since dukaone can reach it, I don't think it's a network problem.

**Comment by gody01** [comment]
Hello,

Can You try with latest version ?
I just pushed new version to github.

**Comment by gody01** [comment]
Also I found out, that fans don't like if they get too many requests at short times.
I also updates pyEcoventV2 to 0.9.6

**Comment by spwtit** [comment]
Do I need to specifically tell HomeAssistant to get pyEcoventV2 in a way?
Still seem to be having the same problems:
Problem 1:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/94296729/155896911-c71e68c7-dc73-4b9c-99a0-cc2eef8a883e.png">
Problem 2:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/94296729/155896920-cb5b7350-7a65-4659-808c-448f5a54d900.png">
Problem 3:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/94296729/155896928-7822da2f-f866-471a-9af5-7b7a9fecb6a0.png">
Problem 4:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/94296729/155896935-02278370-3c7a-4d6a-871c-a4b87f0d1434.png">

Sadly DukaOne does not report the IP adress of the fan, but it does seem to have working broadcast discovery. Because it only really wants the ID from you, the IP ist optional. Where as yours can get the ID, as long as you supply the IP.

Your integration definetly gets some connection to the fan, because if I only supply an IP in the config workflow it results in a success message with the name string +the ID.

Since the first error message above is kinda similar to what I got when playing around with pyEcovent from @aglehmann to just get a connection itself - maybe home assistant doesn't have your version of the library?

**Comment by gody01** [comment]
Hello,
all this kind of messages are indication of Network Connection timeouts.
I'm working on some error reporting but can't publish today.

I also have prototype code for broadcast discovery in place.

I'l publish those during next week.

**Comment by gody01** [comment]
Hello,

I just pushed version 0.4.0 which has some sort of autodetection. If You leave <broadcast> in place od IP address it should scan and find fans on network.

**Comment by itkama** [comment]
@gody01 the update of today definetly changed something. Less error messages. And I was even able to successfully turn on and off a fan. Though the latency is pretty high on that one.
Also still getting a few errors:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/37951363/157983002-5513bd2f-3fe7-4878-af2e-cb3e702cd081.png">
<img width="824" alt="image" src="https://user-images.githubusercontent.com/37951363/157983351-1aab45f7-d430-4083-91c6-9061c43e7a7f.png">

**Comment by gody01** [comment]
@itkama, thanks for testing

I know about latency. It is sometimes high on my production also, where I have lots of deivces on HomeAssistant.

Reported errors indicate as that Your fans wouldn't support battery readings.

Is there any chance, to try with pyEcovent library directly ?

* Clone https://github.com/gody01/pyEcovent
* Then on the computer within same LAN/Wifi as fans run:
** python3 test.py

Perhaps returned print would indicate some more infromation about fans, for example:
* firmware: 0.4 2019-12-20
* battery_voltage: 3262 mV
It seems that latter for example is not reported by Your fans.

BTW: Which version of HomeAssistant do You run ?

**Comment by gody01** [comment]
@itkama,
I pushed new version.
I tried to fix issue with battery voltage and also tried something to lower lattency.

**Comment by itkama** [comment]
@gody01 
Will try to test that out tomorrow, as I currently am not physically at the place with the fans.
I tried the new version though. Latency seems to be better. Battery voltage error still persists. I'm running a couple of Vento Expert A50-1 W V.2 if that helps.

Since I'm for now running the Duka Integration as the main control and yours just for testing I noticed something:
Whenever I switch the fan on or off via your integration the status of the Duka-Fan-Entity reflects that. If I switch via the Duka-Integration, your fan entity does not get updated. Even when setting up the fan your integration didn't seem to notice, that the fan was in fact running. Your fan entity showed it as off.

**Comment by gody01** [comment]
@itkama 
Thanks for testing.

I decided, to go with so called UpdateCoordinator, which means, that integration polls fan only once / 60s for all statuses.
So it will detect that Fan changed status within one minute.

That is for many reasons. Mainly that not so many information is stored in database on HomeAssistant, but also for the reason, that there is not so many network request to fans. As it seems to me, that fans are not very robust when there is lot's of network traffic to them.

For now, I left default 60s polling interval. It can be lovered to lesser time.

**Comment by gody01** [comment]
I checked Duka integration / library and it seems that it updates fan statuses every 4 seconds.

If I put 4 second update and try to control fans from 3 HomeAssistant interfaces I get quite some timeouts.

Can You perhaps test without Duka integration ?
Is battery error still the same as before ? (NoneType has no attribute split) ?

**Comment by itkama** [comment]
Hi @gody01,
sorry for taking so long. Life and a covid infection came along 😅
I've tested it with the Duka One Integration Fans deactivated. I then had your integration search on standard settings via Broadcast. It took a while but found a fan (basically like last time).
Battery voltage problem still exists:
![image](https://user-images.githubusercontent.com/37951363/163715766-6c347356-a961-4db9-859a-54bfbb528f22.png)
It also seems to have problem with the fan filters in a similar way:
![image](https://user-images.githubusercontent.com/37951363/163715781-90db95f0-0e5f-4b9a-9615-8e7322babbdc.png)

I also attached the output of test.py. To me it looks like they are reporting basically nothing - just the Device ID which was discovered.
[test-output.txt](https://github.com/gody01/ecovent_v2/files/8501634/test-output.txt)

**Comment by gody01** [comment]
Is this working now ?
Fans hase to be in master mode, to report anything.

**Comment by itkama** [comment]
Hi Matjaž,
I'm afraid I have not tested it any further as the Duka One Integration is running more or less flawlessly 😅

**Comment by gody01** [comment]
Excellent,
I'll close this issue ...
